<?
$emailMessage = createCMEText($name, $data["yourEmail"], $data["title"], 
	$selectedSections, $data["searching"], $data["found"], 
	$selectedLearningsStrings, $data["date"], $creditString);

//Generate and return email text based on specified strings
//"\t\n" is used instead of just "\n" to ensure that Outlook formats the email 
//properly. (with just "\n" it will often ignore the newline)
function createCMEText($name, $yourEmail, $title, $selectedSections, $searching, 
			$found, $selectedLearnings, $date, $creditType) {		
	if(strlen($searching) < 1) { $searching = "(none)"; }
	if(strlen($found) < 1) { $found = "(none)"; }
	$learnings = join($selectedLearnings, '</li><li>');
	$sections = join($selectedSections, '</li><li>');	
	$email = <<<EOD
<html>
<head>
<title>DynaMed CME Request</title>
</head>
<body style="color: #000;padding:20px; font-size: 11px; font-family: verdana, sans-serif !important;">
<div style="padding: 0px 10px 10px 10px; text-align: center;">
<h1 style="color: #000;font-size: 14px; margin-top: 0.75em; font-weight: bold">DynaMed CME credit for {$name} - {$date}</h1>
<p style="padding-top: 0px;"><i>Type of Credit Requested:</i> {$creditType}<br/>
<i>User's Email Address:</i> {$yourEmail}</p>
</div>
<div style="padding: 0px 20px 0px 20px; background: #f8f8f8; padding: 10px; color: #444; font-size: 10px;">
The following is a request for DynaMed CME credit.
This request has been sent to your CME coordinator.
For more information on your DynaMed CME request, please
<a href="http://support.epnet.com/knowledge_base/detail.php?id=3162">click here</a>
</div>
<div style="padding: 0px 20px 0px 20px">
<h2 style="color: #000;font-size: 12px; font-weight: bold; margin-top: 1.5em">{$name} was searching for "<i>{$title}</i>" and reviewed content in the following sections:</h2>
<ul style="padding-left:4em; list-style:square"><li>{$sections}</li></ul>
<p><i>Comments:</i> {$searching}</p>
</div>
<div style="padding: 0px 20px 0px 20px">
<h2 style="color: #000;font-size: 12px; font-weight: bold; margin-top: 1.5em">In the sections indicated above {$name} found DynaMed content for "<i>{$title}</i>".</h2>
<p><i>Comments:</i> {$found}</p>
</div>
<div style="padding: 0px 20px 0px 20px">
<h2 style="color: #000;font-size: 12px; font-weight: bold; margin-top: 1.5em">The following statements apply:</h2>
<ul style="padding-left:4em; list-style:square"><li>{$learnings}</li></ul>
</div>
<p style="margin-top: 15px; text-align: center;background: #f8f8f8; padding: 10px; color: #444; font-size: 10px;">
E-mail Disclaimer: This e-mail was generated by a user of DynaMed. Please do not reply to this message.
Neither EBSCO nor the institution from which this e-mail was created are responsible for the content of this e-mail.
If you have any problems or questions, contact Technical Support at http://support.ebscohost.com/contact/askus.php or call 800-758-5995.</p>
</body>
</html>
EOD;
	return $email;
}
?>
