function ebscoHostSearchParse(ebscohostsearchtext) {
 var sT=ebscohostsearchtext.match(/(\(|\)|[^"^\s^)]+)\s*|"([^"]+)"\s*/gi); var sQ=''; var bP=0; var fP=0; var nP=0;
 for(var i = 0;i<sT.length;i++) { sT[i]=sT[i].replace(/\s+$/,""); switch (sT[i].toUpperCase()) {
 case 'TX': case 'AU': case 'TI': case 'SU': case 'SO': case 'IS': if (sQ.length>nP) if (bP==0) sQ+='\+AND\+'; if (fP==1) sQ+=sT[i]+'\+AND\+'; else if (fP==2) sQ+=sT[i]+'\+'; else sQ+=sT[i]+'\+(\+'; if (fP!=2) fP=1; bP=1; break;
 case 'AA': case 'AB': case 'AC': case 'AD': case 'AE': case 'AF': case 'AG': case 'AI': case 'AK': case 'AL': case 'AM': case 'AN': case 'AO': case 'AP': case 'AR': case 'AS': case 'AT': case 'AV': case 'AW':
case 'AZ': case 'BA': case 'BC': case 'BD': case 'BK': case 'BM': case 'BN': case 'BP': case 'BR': case 'BS': case 'BT': case 'CA': case 'CB': case 'CC': case 'CD': case 'CE': case 'CF': case 'CH': case 'CI': case 'CL': case 'CM': case 'CN': case 'CO': case 'CP': case 'CR': case 'CS': case 'CT': case 'CU': case 'CX': case 'CY': case 'DB': case 'DC': case 'DD': case 'DE': case 'DF': case 'DG': case 'DI': case 'DM': case 'DN': case 'DO': case 'DP': case 'DR': case 'DS': case 'DT': case 'DU': case 'DX': case 'EB': case 'EC': case 'ED': case 'EF': case 'EG': case 'EL': case 'EM': case 'EN': case 'ER': case 'ES': case 'ET': case 'FA': case 'FC': case 'FD': case 'FF': case 'FG': case 'FI': case 'FK': case 'FL': case 'FQ': case 'FR': case 'FS': case 'FT': case 'GB': case 'GC': case 'GD': case 'GE': case 'GI': case 'GL': case 'GN': case 'GR': case 'GS': case 'GT': case 'GV': case 'HC': case 'HJ': case 'HS': case 'HT': case 'HY': case 'IA': case 'IB': case 'IC': case 'ID': case 'II': case 'IM': case 'IN': case 'IP': case 'IR': case 'IV': case 'JI': case 'JN': case 'JS': case 'JT': case 'KK': case 'KT': case 'KW': case 'KY': case 'LA': case 'LB': case 'LC': case 'LE': case 'LG': case 'LH': case 'LI': case 'LL': case 'LN': case 'LS': case 'LT': case 'LV': case 'LW': case 'MA': case 'MB': case 'MC': case 'MD': case 'ME': case 'MF': case 'MH': case 'MI': case 'MJ': case 'MM': case 'MN': case 'MO': case 'MP': case 'MQ': case 'MR': case 'MS': case 'MT': case 'MV': case 'MW': case 'NA': case 'NB': case 'NC': case 'NE': case 'NF': case 'NI': case 'NM': case 'NN': case 'NO': case 'NP': case 'NR': case 'NS': case 'NT': case 'NU': case 'OA': case 'OC': case 'OD': case 'OG': case 'OL': case 'OP': case 'OS': case 'OT': case 'PA': case 'PB': case 'PC': case 'PD': case 'PE': case 'PG': case 'PH': case 'PI': case 'PL': case 'PM': case 'PN': case 'PO': case 'PP': case 'PR': case 'PS': case 'PT': case 'PU': case 'PY': case 'PZ': case 'QT': case 'RA': case 'RC': case 'RD': case 'RE': case 'RF': case 'RJ': case 'RN': case 'RO': case 'RP': case 'RR': case 'RS': case 'RT': case 'RV': case 'RW': case 'SA': case 'SB': case 'SC': case 'SD': case 'SE': case 'SG': case 'SH': case 'SI': case 'SJ': case 'SK': case 'SL': case 'SM': case 'SN': case 'SP': case 'SQ': case 'SS': case 'ST': case 'SX': case 'SY': case 'TA': case 'TC': case 'TD': case 'TH': case 'TK': case 'TL': case 'TM': case 'TN': case 'TP': case 'TR': case 'TS': case 'TT': case 'TU': case 'TY': case 'UC': case 'UD': case 'UI': case 'UP': case 'UR': case 'UT': case 'VC': case 'VI': case 'VS': case 'VT': case 'XN': case 'XY': case 'YR': if (sQ.length>nP) if (bP==0) sQ+='\+AND\+'; if (fP==1) sQ+=sT[i]+'\+AND\+'; else if (fP==2) sQ+=sT[i]+'\+'; else sQ+=sT[i]+'\+'; if (fP!=1) fP=2; bP=1; break;
 case '(': if (sQ.length>nP && bP==0) { if (fP!=2) sQ+='\+AND\+'; else sQ+='\+'; } if (fP!=1) sQ+='(\+'; bP=1; nP+=1; break; case ')': sQ+='\+)'; bP=1; fP=0; nP-=1; break;
 case 'AND': case 'OR': case 'NOT': if (sQ.length>nP && fP==1 && nP<1) sQ+='\+)'; sQ+='\+'+sT[i]+'\+'; bP=1; fP=0; break;
 default: if (sT[i].search(/^w([01]?\d\d?|2[0-4]\d|25[0-5])$/)!=-1||sT[i].search(/^n([01]?\d\d?|2[0-4]\d|25[0-5])$/)!=-1) { if (sQ.length>nP && fP>=1) sQ+='\+)'; sQ+='\+'+sT[i]+'\+'; bP=1; fP=0; break; } else { if (sQ.length>nP && bP==0) { if (fP!=2) sQ+='\+AND\+'; else sQ+='\+'; } sQ+=sT[i]; bP=0; } } }
 if (fP==1) sQ+='\+)'; sQ=sQ.replace(/\"/g,"%22"); sQ=sQ.replace(/ /g,"+"); return sQ; }

function ebscoHostSearchGo(form) { var ebscohostsearchtext=form.ebscohostsearchtext.value; if (ebscohostsearchtext=="") alert("Please enter search term(s)."); else { var ebscohostkeywords=form.ebscohostkeywords.value; var ebscohostwindow=form.ebscohostwindow.value; var ebscohosturl=form.ebscohosturl.value; if(ebscohostkeywords!="") ebscohostkeywords=ebscoHostSearchParse(ebscohostkeywords)+'\+AND\+'; ebscohosturl=ebscohosturl+'('+ebscohostkeywords+ebscoHostSearchParse(ebscohostsearchtext)+')'; if (ebscohostwindow == 1) window.open(ebscohosturl,'EBSCOhost'); else document.location=ebscohosturl; } } }